### PR TITLE
Fix: Config option hub.forkrepo was ignored

### PR DESCRIPTION
**Pull request by Marenz**
In the whole file, the string `forkrepo` only appears in the config class..

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
Interesting. I wonder why this was allowed to be overridden, as normally it should be `<user>/<repo>`. Maybe to work in some weird setup where you have this workflow but not in your private repo. In this case I wonder if we should have an option for `git hub clone` too to use a different `forkrepo` (and probably set the variable)?

Do you have a usercase for this or you detected it just by chance?

**Comment by Marenz** [comment]
My workflow is that I only use the same repo for the source & target branch. That's when I found this problem

**Comment by leandro-lucarella-sociomantic** [comment]
> My workflow is that I only use the same repo for the source & target branch. That's when I found this problem

Ah, OK, I wonder if it would be nice to add a command line option to override this...

**Comment by leandro-lucarella-sociomantic** [comment]
This pull request has been rebased via `git hub pull rebase`. Original pull request HEAD was ca51d56ca14fa956d6c0ab18073c1a01672714ff, new (rebased) HEAD is a1219e9c6edd55855756ea58e4659a9b5903621c

**Pull request closed without merging**
