### PR TITLE
More options for issues list

### PR DESCRIPTION
**Pull request by bdilly**
I need them to generate a report.

It may be useful for more people.

### CODE REVIEW

**Comment by llucax** [comment]
Sorry for the delay, I was ill. I'll review it soon!

**Comment by bdilly** [comment]
@llucax It's ok. I hope you're better now =)

**Comment by llucax** [comment]
Oh, damn... I forgot about this again...

About the formatting options, I think at one point we need to just include an option to allow custom formatting, this approach doesn't scale. Many people will want different formats, so I'd like to see something like `--format '#{number} {title}'` in the future instead. If you are willing to implement it, awesome, otherwise I will merge this PR (but probably add a TODO note so people don't feel tempted to add even more formatting options).

As for the filtering options, more or less the same, it doesn't scale either, but it might be more complex to implement correctly. Ideally there should be some kind of filtering like in GitHub search (`--filter 'is:pr is:open updated:>2015'). Again, if you want to implement it, awesome but otherwise I can merge as is.

Finally, I do really think the formatting option shouldn't look like a filter option, so maybe rename `--titles-only` to `--show-only-titles` or something like that? At first by looking at the option names I thought the `--issues-only` was also some sort of formatting option.

**Comment by llucax** [comment]
Oh, look at that: https://developer.github.com/v3/search/#search-issues

Maybe is not hard to implement at all, we can just send the user's query as is to GitHub.

**Comment by llucax** [comment]
BTW, I think the `issue list` command should only return issues. There is a `pull list` command to retrieve pull requests. I think it was like that before, but at some point GitHub unified (even more) issues and PRs. So I would remove the `--issues-only` option and just make `{issue,pull} list` return only the requested type.

As for the filtering, it might make more sense to be just extra positional arguments, so `git hub issue list -f '#{number} {title}' is:pr is:open milestone:v0.10`. Now **that** looks good ;-)

**Comment by llucax** [comment]
(by default `is:issue` should be included in the query for issues and `is:pr` for pull requests)

**Comment by leandro-lucarella-sociomantic** [comment]
@bdilly I know I don't have the right to ask this after forgetting about this PR for 2 months, but... are you still there? :)

**Comment by bdilly** [comment]
@leandro-lucarella-sociomantic yeah, yeah, I am.
I like the idea of custom formats. I'll take a look in github api soon and I'll send a new pull request considering your comments.
Thanks

**Comment by leandro-lucarella-sociomantic** [comment]
:+1:

**Pull request closed without merging**
