### PR TITLE
Verbose cloning causes UnicodeDecodeError in debugf().

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
```
$ git hub -v clone sociomantic/git-hub
...
https://api.github.com/user/repos?page=3
Content-length: 0
Content-type: application/json
Authorization: <hidden>
Accept: application/vnd.github.v3+json
None
Traceback (most recent call last):
  File "/usr/bin/git-hub", line 2017, in <module>
    main()
  File "/usr/bin/git-hub", line 2011, in main
    args.run(parser, args)
  File "/usr/bin/git-hub", line 615, in check_config_and_run
    cmd.run(parser, args)
  File "/usr/bin/git-hub", line 769, in run
    '{}/{}'.format(owner, proj))
  File "/usr/bin/git-hub", line 813, in set_not_own_repo_params
    for repo in req.get('/user/repos'):
  File "/usr/bin/git-hub", line 479, in <lambda>
    self.json_req(url, method, *args, **kwargs)
  File "/usr/bin/git-hub", line 457, in json_req
    debugf("Response:\n{}", data)
  File "/usr/bin/git-hub", line 74, in debugf
    localeprintf(sys.stdout, fmt, *args, **kwargs)
  File "/usr/bin/git-hub", line 65, in localeprintf
    msg = fmt.decode(encoding, 'replace').format(*args, **kwargs) + '\n'
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 124672: ordinal not in range(128)
```

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
Fix attached and fingers crossed so everything doesn't :boom:

**Comment by jwilk** [comment]
0625f4dd4e99 looks good to me!

**Comment by leandro-lucarella-sociomantic** [comment]
@mihails-strasuns-sociomantic is sick so I will just auto-merge.

**Comment by leandro-lucarella-sociomantic** [comment]
This pull request has been rebased via `git hub pull rebase`. Original pull request HEAD was 0625f4dd4e993fda7ecbbb251288e4719cde8707, new (rebased) HEAD is 13931c145b9783ae06cc04c000d8c6ce8e1c8be4

**Pull request closed without merging**
