### PR TITLE
Asorted fixes

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
A few fixes to pull rebase --delete-branch and --pause, and also always
generate a new token, as GitHub API no longer return existing tokens.

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
I'm not entirely happy about generating new tokens, after all having "dangling" tokens is a security risk. Maybe I should just remove the old token and create a new one, but that might break other applications using the token.

Any other ideas?

**Comment by mihails-strasuns-sociomantic** [comment]
It would make impossible using `git-hub` from different workstations for one account simultaneously, right? :( Do they justify API change in any way?

**Comment by leandro-lucarella-sociomantic** [comment]
> Do they justify API change in any way?

I haven't read anything in particular. Maybe in the name of security?

> It would make impossible using git-hub from different workstations for one account simultaneously,

True. Then maybe just failing if a token exist and add an option to choose a different, user-defined, token name?

**Comment by leandro-lucarella-sociomantic** [comment]
BTW, I just removed the change to the auth token from this PR, as the fixes should be probably merged without much discussion. I made a separate PR for the auth token thingy: #133

**Comment by mihails-strasuns-sociomantic** [comment]
This pull request has been rebased via `git hub pull rebase`. Original pull request HEAD was e708973c5fdbca7539ecd964bc36e0cf4761f76a, new (rebased) HEAD is 858060222c4158526aeb5c6791bcd5757ba66849

**Pull request closed without merging**
