### PR TITLE
Don't ignore prefix for bash_completion

### PR DESCRIPTION
**Pull request by jean**

### CODE REVIEW

**Comment by jean** [comment]
I see this was already visited in https://github.com/sociomantic/git-hub/commit/03aa90dee2f37c048abcc97c21be2a0891b99848
But it fixed a different issue. I guess I don't understand why manpages and vim config should go under `$(prefix)`, but not bash completion ..

**Comment by mihails-strasuns-sociomantic** [comment]
Thank you.

Sadly, main `git-hub` author ( @leandro-lucarella-sociomantic ) is currently on holiday so this may need to wait a week or two until his approval.

**Comment by leandro-lucarella-sociomantic** [comment]
> I guess I don't understand why manpages and vim config should go under $(prefix), but not bash completion ..

Because bash_completion is in `/etc` which usually is a bit special, even when your prefix is `/usr`, you want stuff to be installed in the real `/etc`. This is at least true when creating distribution packages.

The only solution I see for this is to just use a variable for where to install the bash_completion script (defaulting to the current value), or maybe a more generic `/etc` override: `sysconfdir := /etc` and then `$(DESTDIR)$(sysconfdir)/bash_completion.d/git-hub`.

**Comment by leandro-lucarella-sociomantic** [comment]
BTW, the `install` target is highly oriented to Debian systems and I wanted to keep it simple as long as possible, but maybe is time to make it more flexible :)

**Comment by leandro-lucarella-sociomantic** [comment]
ping

**Comment by leandro-lucarella-sociomantic** [comment]
Closing due to lack of activity, please feel free to reopen if you are willing to address the mentioned issues.

**Pull request closed without merging**
